/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Configuration for a `<cob-viz>` web component to generate a map from a number of data sources.
 */
export interface VizWizV10 {
  /**
   * Version of the VizWiz configuration format. For this schema, should be "1.0".
   */
  version?: string;
  /**
   * Unique ID for the visualization.
   */
  uid?: string;
  /**
   * Definitions for the layers to include on the map.
   */
  dataSources?: DataSource[];
  /**
   * Definition for the map to render. Defined as an array for future expansion, but currently only one map is rendered.
   */
  maps?: Map[];
}
/**
 * Configuration for a feed of geo data. E.g. a specific ArcGIS service layer.
 */
export interface DataSource {
  /**
   * Unique ID for this data source
   */
  uid?: string;
  /**
   * Configuration for how point features are rendered. Set to `null` to keep these from rendering.
   */
  icons?: null | IconStyle;
  /**
   * Configuration for how line and polygon features are rendered. Set to `null` to keep these from rendering.
   */
  polygons?: null | VectorStyle;
  /**
   * A mustache template for the HTML to render in the popup that appears when the user clicks on the feature. The feature’s ArcGIS attributes will be in scope for the template, and can be referenced with `{{…}}`.
   */
  popupHtmlTemplate?: string;
  /**
   * Configuration for where to load the data source from.
   */
  data?: ArcGisFeatureService;
  /**
   * Options for how this layer is rendered in the legend. Set to `null` to keep the layer from appearing in the legend.
   */
  legend?: null | LegendStyle;
}
export interface IconStyle {
  /**
   * URL for an SVG image to place at the marker point.
   */
  markerUrl?: string;
  /**
   * Whether icons that are close to each other should be collapsed together using the Leaflet.markerCluster plugin.
   */
  cluster?: boolean;
}
export interface VectorStyle {
  /**
   * The name of a preset in the VizWiz UI.
   */
  style?: string;
  /**
   * Hex color to use as the stroke color on features. If a fill is applied, it will be this color at a semi-transparent opacity.
   */
  color?: string;
  /**
   * Hex color to use as the stroke color on features when the mouse is hovered over them. If a fill is applied, it will be this color at a semi-transparent opacity.
   */
  hoverColor?: string;
}
export interface ArcGisFeatureService {
  /**
   * The type of data source. Currently only layers from Esri’s ArcGIS servers are supported.
   */
  type?: 'arcgis';
  /**
   * URL for the feature service on the ArcGIS server. Should not end in a slash.
   */
  service?: string;
  /**
   * The number of the specific layer in the feature service to display.
   */
  layer?: number;
}
export interface LegendStyle {
  /**
   * * `icon`: Shows the `markerUrl` icon from `icons`.
   * * `line`: Renders a line with the `color` from the `polygons` configuration.
   * * `polygon`: Renders a box with the `color` from the `polygons` configuration, with a semitransparent fill.
   */
  symbol?: 'icon' | 'line' | 'polygon';
  /**
   * The label to show in the legend for this layer.
   */
  label?: string;
}
export interface Map {
  /**
   * Unique ID for the map.
   */
  uid?: string;
  /**
   * Title for the map that appears as a label for the “overlay” dropdown on narrow breakpoints.
   */
  title?: string;
  /**
   * HTML to be placed in the overlay to explain how to use the map.
   */
  instructionsHtml?: string;
  /**
   * Latitude for the center of the map
   */
  latitude?: number;
  /**
   * Longitude for the center of the map
   */
  longitude?: number;
  /**
   * Zoom level for the map
   */
  zoom?: number;
  /**
   * Whether or not to show Leaflet’s +/- zoom buttons on the map.
   */
  showZoomControl?: boolean;
  /**
   * Whether or not to show a legend in the overlay box.
   */
  showLegend?: boolean;
  /**
   * Whether or not to get the user’s location with location services and display it on the map.
   */
  showUserLocation?: boolean;
  /**
   * Configuration for adding an address search box to the overlay. Leave `null` to not show the box.
   */
  addressSearch?: null | AddressSearch;
}
export interface AddressSearch {
  /**
   * Title above the search box
   */
  title?: string;
  /**
   * Placeholder to go within the search box when it’s empty.
   */
  placeholder?: string;
  /**
   * If true, the map will zoom in close to a search result after it’s found.
   */
  zoomToResult?: boolean;
  /**
   * If not `null`, will open the popup for the specified layer when the search result is chosen.
   */
  autoPopupDataSourceUid?: null | string;
}
