/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Development version of the VizWiz config JSON
 */
export interface VizWizV00 {
  vizId?: string;
  title?: string;
  description?: string;
  dataSources?: DataSource[];
  maps?: Map[];
}
export interface DataSource {
  uid?: string;
  type?: 'cob-arcgis';
  attributes?: {
    service?: string;
    layer?: number;
  };
  icon?: string;
  clusterIcons?: boolean;
  polygonStyle?: {
    name?: string;
    color?: string | null;
    hoverColor?: string | null;
    [k: string]: any;
  };
  legendLabel?: string;
  popover?: string;
}
export interface Map {
  uid?: string;
  latitude?: number | null;
  longitude?: number | null;
  zoom?: number | null;
  showZoomControl?: boolean;
  showLegend?: boolean;
  findUserLocation?: boolean;
  searchForAddress?: boolean;
  zoomToAddress?: boolean;
  placeholderText?: string;
  addressSearchPopupDataSourceUid?: string;
}
