title: "metrolist"
handle: "metrolist"
status: "ready"
context:
  defaultIcon: "https://www.boston.gov/modules/custom/bos_content/modules/node_post/default_news.svg"
  icons:
    - file: "deposit_check.png"
    - file: "deposit_check.svg"
    - file: "deposit_check@2x.png"
    - file: "deposit_check@3x.png"
    - file: "family2.png"
    - file: "family2.svg"
    - file: "family2@2x.png"
    - file: "family2@3x.png"
    - file: "five-people.png"
    - file: "five-people.svg"
    - file: "five-people@2x.png"
    - file: "five-people@3x.png"
    - file: "four-people.png"
    - file: "four-people.svg"
    - file: "four-people@2x.png"
    - file: "four-people@3x.png"
    - file: "house-loading.gif"
    - file: "house-loading.svg"
    - file: "house-loading@2x.gif"
    - file: "house-loading@3x.gif"
    - file: "house-missing.png"
    - file: "house-missing.svg"
    - file: "house-missing@2x.png"
    - file: "house-missing@3x.png"
    - file: "icon-details-marker.png"
    - file: "icon-details-marker.svg"
    - file: "icon-details-marker@2x.png"
    - file: "icon-details-marker@3x.png"
    - file: "metrolist-logo.png"
    - file: "metrolist-logo.svg"
    - file: "metrolist-logo@2x.png"
    - file: "metrolist-logo@3x.png"
    - file: "person.png"
    - file: "person.svg"
    - file: "person@2x.png"
    - file: "person@3x.png"
    - file: "six-people.png"
    - file: "six-people.svg"
    - file: "six-people@2x.png"
    - file: "six-people@3x.png"
    - file: "two-people.png"
    - file: "two-people.svg"
    - file: "two-people@2x.png"
    - file: "two-people@3x.png"
