title: Footer
handle: footer
status: ready
context:
  links:
    - name: Mayor Kim Janey
      href: https://www.boston.gov/departments/mayors-office/kim-janey
    - name: Privacy Policy
      href: https://www.boston.gov/copyright/privacyandsecurity.asp
    - name: Careers
      href: https://www.boston.gov/departments/human-resources/career-center
