title: How-To Tab
handle: ht-tab
status: ready
variants:
  - name: JS Controlled
    context:
      tabs:
        - title: 'November 8, 2016: General Election'
          js: true
        - title: 'November 8, 2016: General Election'
          js: true
          variant: 'ht-tab--open'
context:
  tabs:
    - index: 1
      title: 'November 8, 2016: General Election'
      content: '<p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p>'
