title: Group of Links
handle: group_links
status: ready
preview: '@centered-grey'
variants:
  - name: Grid Without Description
    context:
      header:
        title: Test Group of Links - Grid Without Description
        contact: 
          title: Boston Team
          link: https://d8-uat.boston.gov/departments/digital-team
      cards:
        - index: 1
          variant: document
          href: https://d8-uat.boston.gov/sites/default/files/linked/file/document_files/2017/03/pdf_for_website_testing_0.pdf
          title: 'Test Link - Document'
          subtitle: 'Test link with document'
          content: '123-456-7890'
        - index: 2
          variant: external
          href: https://www.google.com/
          title: 'Test Link - External'
          subtitle: 'Test link with external link'
          content: 'Test@Boston.gov'
        - index: 3
          variant: false
          href: https://d8-uat.boston.gov/departments/digital-team
          title: 'Test Link - Internal'
          subtitle: 'Test link with internal link'
          content: '123-456-7890' 
  - name: Grid With Description
    context:
      header:
        title: Test Group of Links - Grid With Description
        contact: 
          title: Boston Team
          link: https://d8-uat.boston.gov/departments/digital-team
      subheader:
        title: 'Subheader text'
        description: 'Testing group of links - grid with description and with a CTA as document'
        button: 
          name: 'CTA as document'
          href: https://d8-uat.boston.gov/sites/default/files/linked/file/document_files/2017/03/pdf_for_website_testing_0.pdf
      cards:
        - index: 1
          variant: document
          href: https://d8-uat.boston.gov/sites/default/files/linked/file/document_files/2017/03/pdf_for_website_testing_0.pdf
          title: 'Test Link - Document'
          subtitle: 'Test link with document'
          content: '123-456-7890'
        - index: 2
          variant: external
          href: https://www.google.com/
          title: 'Test Link - External'
          subtitle: 'Test link with external link'
          content: 'Test@Boston.gov'
        - index: 3
          variant: false
          href: https://d8-uat.boston.gov/departments/digital-team
          title: 'Test Link - Internal'
          subtitle: 'Test link with internal link'
          content: '123-456-7890'
context:
  header:
    title: Test Group of Links - Grid Without Description
    contact: 
      title: Boston Team
      link: https://d8-uat.boston.gov/departments/digital-team
  cards:
    - index: 1
      variant: document
      href: https://d8-uat.boston.gov/sites/default/files/linked/file/document_files/2017/03/pdf_for_website_testing_0.pdf
      title: 'Test Link - Document'
      subtitle: 'Test link with document'
      content: '123-456-7890'
    - index: 2
      variant: external
      href: https://www.google.com/
      title: 'Test Link - External'
      subtitle: 'Test link with external link'
      content: 'Test@Boston.gov'
    - index: 3
      variant: false
      href: https://d8-uat.boston.gov/departments/digital-team
      title: 'Test Link - Internal'
      subtitle: 'Test link with internal link'
      content: '123-456-7890'