title: How-To Tabs
handle: ht-tabs
status: ready
variants:
  - name: default open
    status: 'ready'
    context:
      tabs:
        - index: 1
          title: 'Option 1'
          content: '<p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p>'
          open: true
        - index: 2
          title: 'Option 2'
          content: '<p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p>'
context:
  header:
    title: How-To Tabs
    contact: false
  tabs:
    - index: 1
      title: 'Option 1'
      content: '<p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p>'
    - index: 2
      title: 'Option 2'
      content: '<p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p>'
    - index: 3
      title: 'Option 3'
      content: '<p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p>'
    - index: 4
      title: 'Option 4'
      content: '<p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p>'
    - index: 5
      title: 'Option 5'
      content: '<p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p>'
