username: 'Digital Team Notices'
icon_url: https://boston.gov/digitalteamicon.png

pretext: A production deployment has been completed and release notes have been published.
title: <{{payload.release.html_url}}|Code Release>
title_link: {{payload.release.html_url}}
text: |
  A new release has been made for {{payload.repository.name}}.
  *{{payload.repository.description}}*
fallback: |-
  [GitHub] {{payload.release.name}} is released for {{repositoryName}}
blocks:
  - type: context
    elements: 
      - type: mrkdwn
        text: test text
footer: >-
  {{payload.enterprise.name}}, {{payload.repository.name}} <{{payload.release.html_url}}|Code Release>
colors:
  success: '#5DADE2'
  failure: '#884EA0'
  cancelled: '#A569BD'
  default: '#7D3C98'

icons:
  success: ':white_check_mark:'
  failure: ':grimacing:'
  cancelled: ':x:'
  skipped: ':heavy_minus_sign:'
  default: ':interrobang:'
