title: Link Card Mini
handle: link-card-mini
status: ready
preview: '@centered'
variants:
  - name: Mini Document
    context:
      cards:
        - index: 1
          variant: 'lcd--mini'
          image: 
            url: /images/global/icons/icon-document.svg
          href: https://d8-uat.boston.gov/sites/default/files/linked/file/document_files/2017/03/pdf_for_website_testing_0.pdf
          title: 'Test Link - Document'
  - name: Mini External
    preview: '@centered'
    context:
      cards:
        - index: 1
          # image: 
          #   url: /images/global/icons/external-link.svg
          #   title: 'External Link'
          href: https://www.google.com/
          title: 'Test Link - External'
  - name: Mini Internal
    preview: '@centered'
    context:
      cards:
        - index: 1
          # image: false
          href: https://d8-uat.boston.gov/departments/digital-team
          title: 'Test Link - Internal'
context:
  cards:
    - index: 1
      # image: 
      #   url: 
      #   title: 'Link'
      href: https://d8-uat.boston.gov/departments/digital-team
      title: 'Test Link'
      subtitle: 'Test link with link'
      content: 'Test@Boston.gov'
