title: Link Card Mini
handle: link-card-mini
status: ready
preview: '@centered'
variants:
  - name: Mini Document
    context:
      cards:
        - index: 1
          variant: 'document'
          href: https://d8-uat.boston.gov/sites/default/files/linked/file/document_files/2017/03/pdf_for_website_testing_0.pdf
          title: 'Test Link - Document'
  - name: Mini External
    preview: '@centered'
    context:
      cards:
        - index: 1
          variant: 'external'
          href: https://www.google.com/
          title: 'Test Link - External'
  - name: Mini Internal
    preview: '@centered'
    context:
      cards:
        - index: 1
          variant: false
          href: https://d8-uat.boston.gov/departments/digital-team
          title: 'Test Link - Internal'
context:
  cards:
    - index: 1
      variant: false
      href: https://d8-uat.boston.gov/departments/digital-team
      title: 'Test Link'
      subtitle: 'Test link with link'
      content: 'Test@Boston.gov'
