title: Resource Card 2
handle: resource-2
status: ready
preview: '@centered'
context:
  cards:
  - description: 'Your Mayor'
    name: Kim Janey
    position: Mayor
    image: https://d8-uat.boston.gov/sites/default/files/linked/styles/150_embedded_ckeditor/public/img/library/photos/2021/03/janey-headshot2.jpg?itok=IPskEHvW
