title: Grid of Icon Cards
handle: grid_icon_cards
status: ready
preview: '@centered'
context:
  header:
    title: Grid of Icon Cards
    contact: false
  cards:
    - index: 1
      href: https://www.boston.gov/
      icon:
        url: /images/global/icons/experiential/private-group-meeting-.svg
      title: 'Representation'
      content: 'Your representation and voting information'
    - index: 2
      href: https://www.boston.gov/
      icon:
        url: /images/global/icons/experiential/food-truck.svg
      title: 'City Services'
      content: 'Trash / recycling pick up and street sweeping.'
    - index: 3
      href: https://www.boston.gov/
      icon:
        url: /images/global/icons/experiential/311.svg
      title: 'Report an issue to 311'
      content: 'Ways to report non-emergency issues.'

