title: Grid of Icon Cards
handle: grid_icon_cards
status: ready
context:
  header:
    title: Grid of Icon Cards
    contact: false
  cards:
    - index: 1
      href: https://www.boston.gov/neighborhood/allston
      icon:
        url: /images/global/icons/experiential/private-group-meeting-.svg
      title: 'Representation'
      content: 'Your representation and voting information'
    - index: 2
      href: https://www.boston.gov/neighborhood/allston
      icon:
        url: /images/global/icons/experiential/food-truck.svg
      title: 'City Services'
      content: 'Trash / recycling pick up and street sweeping.'

