title: Resource Card 3
handle: resource-3
status: ready
preview: '@centered'
context:
  cards:
  - description: Your Mayor
    href: https://www.boston.gov
    image: https://www.boston.gov/sites/default/files/styles/person_profile_card_173x173_/public/img/library/photos/2021/03/new-janey-headshot.jpg
    name: Kim Janey
    row1: Mayor
    row2: Learn more about
    link:
      href: https://www.boston.gov/
      text: Boston's Mayor
    row2-cont: '.'