title: Tab
handle: tab
status: ready
variants:
  - name: Mini
    context:
      tabs:
        - title: 'Filter by title'
          variant: 'dr--sm'
  - name: JS Controlled
    context:
      tabs:
        - title: 'November 8, 2016: General Election'
          subtitle: 'Last updated: 2/2017'
          js: true
        - title: 'November 8, 2016: General Election'
          subtitle: 'Last updated: 2/2017'
          js: true
          variant: 'dr--open'
context:
  tabs:
    - index: 1
      title: 'November 8, 2016: General Election'
      subtitle: 'Last updated: 2/2017'
      content: '<p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p>'
