includes:
  - ../../variables.yml
localvariable: Full Name
title: Grid of People
handle: grid_person_cards
status: ready
variants:
  - name: hub
    preview: '@hub'
context:
  header:
    title: City Government
    contact: false
  people:
    - name: {fullname}
      position: Mayor
      image: https://www.boston.gov/sites/default/files/styles/person_photo_profile_large_360x360_/public/img/library/photos/2021/03/new-janey-headshot.jpg
      contact: mailto:mayor@boston.gov
      url: https://www.boston.gov/mayor
      grid: g--1 g--3--sl
    - name: Mayor Kim Janey
      position: Mayor
      image: https://www.boston.gov/sites/default/files/styles/person_photo_profile_large_360x360_/public/img/library/photos/2021/03/new-janey-headshot.jpg
      contact: mailto:mayor@boston.gov
      url: https://www.boston.gov/mayor
      grid: g--1 g--3--sl
    - name: Kim Janey
      position: Mayor of the City of Boston in the Commonwealth of Massachusetts.
      image: https://www.boston.gov/sites/default/files/styles/person_photo_profile_large_360x360_/public/img/library/photos/2021/03/new-janey-headshot.jpg
      contact: mailto:mayor@boston.gov
      url: https://www.boston.gov/mayor
      grid: g--1 g--3--sl
    - name: Mayor Kim Janey
      position: Mayor
      image: https://www.boston.gov/sites/default/files/styles/person_photo_profile_large_360x360_/public/img/library/photos/2021/03/new-janey-headshot.jpg
      contact: mailto:mayor@boston.gov
      url: https://www.boston.gov/mayor
      grid: g--1 g--3--sl
    - name: Mayor Kim Janey
      position: Mayor
      image: https://www.boston.gov/sites/default/files/styles/person_photo_profile_large_360x360_/public/img/library/photos/2021/03/new-janey-headshot.jpg
      contact: mailto:mayor@boston.gov
      url: https://www.boston.gov/mayor
      grid: g--1 g--3--sl
    - name: Mayor Kim Janey
      position: Mayor
      image: https://www.boston.gov/sites/default/files/styles/person_photo_profile_large_360x360_/public/img/library/photos/2021/03/new-janey-headshot.jpg
      contact: mailto:mayor@boston.gov
      url: https://www.boston.gov/mayor
      grid: g--1 g--3--sl
    - name: Mayor Kim Janey
      position: Mayor
      image: https://www.boston.gov/sites/default/files/styles/person_photo_profile_large_360x360_/public/img/library/photos/2021/03/new-janey-headshot.jpg
      contact: mailto:mayor@boston.gov
      url: https://www.boston.gov/mayor
      grid: g--1 g--3--sl
    - name: Mayor Kim Janey
      position: Mayor
      image: https://www.boston.gov/sites/default/files/styles/person_photo_profile_large_360x360_/public/img/library/photos/2021/03/new-janey-headshot.jpg
      contact: mailto:mayor@boston.gov
      url: https://www.boston.gov/mayor
      grid: g--1 g--3--sl
    - name: Mayor Kim Janey
      position: Mayor
      image: https://www.boston.gov/sites/default/files/styles/person_photo_profile_large_360x360_/public/img/library/photos/2021/03/new-janey-headshot.jpg
      contact: mailto:mayor@boston.gov
      url: https://www.boston.gov/mayor
      grid: g--1 g--3--sl
