title: Group of Links
handle: group_links
status: ready
variants:
  - name: hub
    status: 'ready'
    preview: '@hub'
context:
  header:
    title: Test Group of Links - Grid Without Description
    contact: true
  cards:
    - index: 1
      href: https://d8-uat.boston.gov/sites/default/files/linked/file/document_files/2017/03/pdf_for_website_testing_0.pdf
      title: 'Test Link - Document'
      subtitle: 'Test link with document'
      content: '123-456-7890'
    - index: 2
      href: https://www.google.com/
      title: 'Test Link - External'
      subtitle: 'Test link with external link'
      content: 'Test @ Boston.gov'
    - index: 3
      href: https://d8-uat.boston.gov/departments/digital-team
      title: 'Test Link - Internal'
      subtitle: 'Test link with internal link'
      content: '123-456-7890'