title: Group of Links
handle: group_links
status: ready
variants:
  - name: Grid Without Description
    preview: '@centered-grey'
    context:
      header:
        title: Test Group of Links - Grid Without Description
        contact: 
          title: Boston Team
          link: https://d8-uat.boston.gov/departments/digital-team
      cards:
        - index: 1
          image: 
            url: /images/global/icons/icon-document.svg
          href: https://d8-uat.boston.gov/sites/default/files/linked/file/document_files/2017/03/pdf_for_website_testing_0.pdf
          title: 'Test Link - Document'
          subtitle: 'Test link with document'
          content: '123-456-7890'
        - index: 2
          # image: 
          #   url: /images/global/icons/external-link.svg
          #   title: 'External Link'
          href: https://www.google.com/
          title: 'Test Link - External'
          subtitle: 'Test link with external link'
          content: 'Test@Boston.gov'
        - index: 3
          # image: false
          href: https://d8-uat.boston.gov/departments/digital-team
          title: 'Test Link - Internal'
          subtitle: 'Test link with internal link'
          content: '123-456-7890' 
  - name: Grid With Description
    preview: '@centered-grey'
    context:
      header:
        title: Test Group of Links - Grid With Description
        contact: 
          title: Boston Team
          link: https://d8-uat.boston.gov/departments/digital-team
      cards:
        - index: 1
          # image: 
          #   url: /images/global/icons/icon-document.svg
          #   title: 'Document Link'
          href: https://d8-uat.boston.gov/sites/default/files/linked/file/document_files/2017/03/pdf_for_website_testing_0.pdf
          title: 'Test Link - Document'
          subtitle: 'Test link with document'
          content: '123-456-7890'
        - index: 2
          # image: 
          #   url: /images/global/icons/external-link.svg
          #   title: 'External Link'
          href: https://www.google.com/
          title: 'Test Link - External'
          subtitle: 'Test link with external link'
          content: 'Test@Boston.gov'
        - index: 3
          # image: false
          href: https://d8-uat.boston.gov/departments/digital-team
          title: 'Test Link - Internal'
          subtitle: 'Test link with internal link'
          content: '123-456-7890' 
  - name: Mini Grid Without Description 
    context:
      header:
        title: Test Group of Links - Mini Grid Without Description
        contact: 
          title: Boston Team
          link: https://d8-uat.boston.gov/departments/digital-team
      cards:
      - index: 1
        small: true
        # image: 
        #   url: /images/global/icons/icon-document.svg
        #   title: 'Document Link'
        href: https://d8-uat.boston.gov/sites/default/files/linked/file/document_files/2017/03/pdf_for_website_testing_0.pdf
        title: 'Test Link - Document'
        subtitle: false
        content: false
      - index: 2
        small: true
        # image: 
        #   url: /images/global/icons/external-link.svg
        #   title: 'External Link'
        href: https://www.google.com/
        title: 'Test Link - External'
        subtitle: false
        content: false
      - index: 3
        small: true
        # image: false
        href: https://d8-uat.boston.gov/departments/digital-team
        title: 'Test Link - Internal'
        subtitle: false
        content: false
