title: Group of Links List
handle: group_links_list
status: ready
preview: '@centered-grey'
variants:
  - name: List Without Description
    context:
      header:
        title: Test Group of Links - List Without Description
        contact: 
          title: Boston Team
          link: https://d8-uat.boston.gov/departments/digital-team
      cards:
        - index: 1
          variant: document
          href: https://d8-uat.boston.gov/sites/default/files/linked/file/document_files/2017/03/pdf_for_website_testing_0.pdf
          title: 'Test Link - Document'
          url: '/images/global/icons/icon-document.svg'
          content: 'Description for a document goes here. Description for a document goes here. Description for a document goes here. Description...'
        - index: 2
          variant: external
          href: https://www.google.com/
          title: 'Test Link - External'
          url: '/images/global/icons/external-link.svg'
          content: 'Description for a document goes here. Description for a document goes here. Description for a document goes here. Description...'
        - index: 3
          variant: false
          href: https://d8-uat.boston.gov/departments/digital-team
          title: 'Test Link - Internal'
          content: 'Description for a document goes here. Description for a document goes here. Description for a document goes here. Description...' 
  - name: List With Description
    context:
      header:
        title: Test Group of Links - List With Description
        contact: 
          title: Boston Team
          link: https://d8-uat.boston.gov/departments/digital-team
      subheader:
        title: 'Subheader text'
        description: 'Testing group of links - grid with description and with a CTA as document'
        button: 
          name: 'CTA as document'
          href: https://d8-uat.boston.gov/sites/default/files/linked/file/document_files/2017/03/pdf_for_website_testing_0.pdf
      cards:
        - index: 1
          variant: document
          href: https://d8-uat.boston.gov/sites/default/files/linked/file/document_files/2017/03/pdf_for_website_testing_0.pdf
          title: 'Test Link - Document'
          url: '/images/global/icons/icon-document.svg'
          content: 'Description for a document goes here. Description for a document goes here. Description for a document goes here. Description...'
        - index: 2
          variant: external
          href: https://www.google.com/
          title: 'Test Link - External'
          url: '/images/global/icons/external-link.svg'
          content: 'Description for a document goes here. Description for a document goes here. Description for a document goes here. Description...'
        - index: 3
          variant: false
          href: https://d8-uat.boston.gov/departments/digital-team
          title: 'Test Link - Internal'
          content: 'Description for a document goes here. Description for a document goes here. Description for a document goes here. Description...'
context:
  header:
    title: Test Group of Links - List Without Description
    contact: 
      title: Boston Team
      link: https://d8-uat.boston.gov/departments/digital-team
  cards:
    - index: 1
      variant: document
      href: https://d8-uat.boston.gov/sites/default/files/linked/file/document_files/2017/03/pdf_for_website_testing_0.pdf
      title: 'Test Link - Document'
      url: '/images/global/icons/icon-document.svg'
      content: 'Description for a document goes here. Description for a document goes here. Description for a document goes here. Description...'
    - index: 2
      variant: external
      href: https://www.google.com/
      title: 'Test Link - External'
      url: '/images/global/icons/external-link.svg'
      content: 'Description for a document goes here. Description for a document goes here. Description for a document goes here. Description...'
    - index: 3
      variant: false
      href: https://d8-uat.boston.gov/departments/digital-team
      title: 'Test Link - Internal'
      content: 'Description for a document goes here. Description for a document goes here. Description for a document goes here. Description...'