title: Grid of Quotes
handle: grid-of-quotes
status: ready
variants:
  - name: Hub
    preview: '@centered-hub'
  - name: Grid
    preview: '@grid'
    context:
      quotes:
        - index: 1
          href: 
            url: https://www.boston.gov/neighborhood/allston
            title: 'third space'
          image:
            url: https://patterns.boston.gov/images/global/icons/quote.svg
            title: 'Jeanethe'
          title: 'Jeanethe'
          location: 'Fenway/Kenmore'
          content: 'I’ve received many opportunities to gain more skills and also further my education.'
        - index: 2
          href: 
            url: https://www.boston.gov/neighborhood/allston
            title: 'third space'
          image:
            url: https://patterns.boston.gov/images/global/icons/quote.svg
            title: 'Jeanethe'
          title: 'Jeanethe'
          location: 'Fenway/Kenmore'
          content: 'I’ve received many opportunities to gain more skills and also further my education.'
        - index: 3
          href: 
            url: https://www.boston.gov/neighborhood/allston
            title: 'third space'
          image:
            url: https://patterns.boston.gov/images/global/icons/quote.svg
            title: 'Jeanethe'
          title: 'Jeanethe'
          location: 'Fenway/Kenmore'
          content: 'I’ve received many opportunities to gain more skills and also further my education.'
        - index: 4
          href: 
            url: https://www.boston.gov/neighborhood/allston
            title: 'third space'
          image:
            url: https://patterns.boston.gov/images/global/icons/quote.svg
            title: 'Jeanethe'
          title: 'Jeanethe'
          location: 'Fenway/Kenmore'
          content: 'I’ve received many opportunities to gain more skills and also further my education.'
context:
  header:
    title: Hear From Employees
    contact: false
  quotes:
    - index: 1
      href: 
        url: https://www.boston.gov/neighborhood/allston
        title: 'third space'
      image:
        url: https://patterns.boston.gov/images/global/icons/quote.svg
        title: 'Jeanethe'
      title: 'Jeanethe'
      location: 'Fenway/Kenmore'
      content: 'I’ve received many opportunities to gain more skills and also further my education.'
