title: Sticky Submenu
handle: sticky-submenu
status: ready
variants:
  # - name: centered
  #   context:
  #     theme: c
  # - name: yellow
  #   context:
  #     theme: y
context:
  links:
    - name: Transition Report
      href: https://311.boston.gov/
      # active: true
    - name: Ending Racism
      href: https://311.boston.gov/lookup
    - name: Recognition
      href: https://311.boston.gov/onthego
    - name: Major Reports
      href: https://311.boston.gov/faq
    - name: Initiatives
      href: https://311.boston.gov/faq
