title: Sticky Submenu
handle: sticky-submenu
status: ready
variants:
  - name: Sticky Submenu
    context:
      stickysubmenu: sticky
      drawer:
        name: Page Sections
        toggle: Toggle
        svg:
          iconstroke: M13,17.7L0.5,2.7C0,2.1,0.1,1.2,0.7,0.6c0.6-0.5,1.6-0.4,2.1,0.2L13,13L23.2,0.8c0.5-0.6,1.5-0.7,2.1-0.2 c0.6,0.5,0.7,1.5,0.2,2.1L13,17.7z
      links:
        - name: Transition Report
          href: https://311.boston.gov/
          active: true
        - name: Ending Racism
          href: https://311.boston.gov/lookup
        - name: Recognition
          href: https://311.boston.gov/onthego
        - name: Major Reports
          href: https://311.boston.gov/faq
        - name: Initiatives
          href: https://311.boston.gov/faq  
context:
  drawer:
    name: Page Sections
    toggle: Toggle
    svg:
      iconstroke: M13,17.7L0.5,2.7C0,2.1,0.1,1.2,0.7,0.6c0.6-0.5,1.6-0.4,2.1,0.2L13,13L23.2,0.8c0.5-0.6,1.5-0.7,2.1-0.2 c0.6,0.5,0.7,1.5,0.2,2.1L13,17.7z
  links:
    - name: Transition Report
      href: https://311.boston.gov/
    - name: Ending Racism
      href: https://311.boston.gov/lookup
    - name: Recognition
      href: https://311.boston.gov/onthego
      active: true
    - name: Major Reports
      href: https://311.boston.gov/faq
    - name: Initiatives
      href: https://311.boston.gov/faq
