title: "drupal"
handle: "drupal"
status: "ready"
context:
  defaultIcon: "https://www.boston.gov/modules/custom/bos_content/modules/node_post/default_news.svg"
  icons:
    - file: "archive.svg"
    - file: "delete.svg"
    - file: "edit.svg"
    - file: "new-draft.svg"
    - file: "publish.svg"
    - file: "review.svg"
    - file: "ribbon-black.svg"
    - file: "ribbon-grey.svg"
