title: 'Hero: With Strikethrough Text'
handle: hero-with-strikethrough
status: wip
context:
  home: true
  intro: guide
  title: Winter in Boston
  subheader: Last updated: 1/22/21
  image:
    wide1x: https://www.boston.gov/sites/default/files/styles/intro_image_large_1x/public/img/unk/intro_images/TOPIC-HERO-WINTER_10.jpg?itok=fALuVUVP
    desktop1x: https://www.boston.gov/sites/default/files/styles/intro_image_desktop_1x/public/img/unk/intro_images/TOPIC-HERO-WINTER_10.jpg?itok=6hseBF7x
    tablet1x: https://www.boston.gov/sites/default/files/styles/intro_image_tablet_1x/public/img/unk/intro_images/TOPIC-HERO-WINTER_10.jpg?itok=7lsO-4Cp
    mobile1x: https://www.boston.gov/sites/default/files/styles/intro_image_mobile_1x/public/img/unk/intro_images/TOPIC-HERO-WINTER_10.jpg?itok=mICd2sMr
