title: 'Hero: With Strikethrough Text'
handle: hero-with-strikethrough
status: wip
context:
  home: true
  intro: guide
  title: Winter in Boston
  subheader: Mayor Martin J. Walsh
  image:
    wide1x: https://patterns.boston.gov/assets/images/fleet/boston-header3.jpg
    desktop1x: https://patterns.boston.gov/assets/images/fleet/boston-header3.jpg
    tablet1x: https://patterns.boston.gov/assets/images/fleet/boston-header3.jpg
    mobile1x: https://patterns.boston.gov/assets/images/fleet/boston-header3.jpg
