title: Link Card Mini
handle: link-card-mini
status: ready
preview: '@centered'
variants:
  - name: Document
    context:
      cards:
        - index: 1
          image: 
            url: /images/global/icons/icon-document.svg
            title: 'Document Link'
          href: https://d8-uat.boston.gov/sites/default/files/linked/file/document_files/2017/03/pdf_for_website_testing_0.pdf
          title: 'Test Link - Document'
          subtitle: 'Test link with document'
          content: '123-456-7890'
  - name: External
    context:
      cards:
        - index: 1
          image: 
            url: /images/global/icons/external-link.svg
            title: 'External Link'
          href: https://www.google.com/
          title: 'Test Link - External'
          subtitle: 'Test link with external link'
          content: 'Test@Boston.gov'
  - name: Internal
    context:
      cards:
        - index: 1
          href: https://d8-uat.boston.gov/departments/digital-team
          title: 'Test Link - Internal'
          subtitle: 'Test link with internal link'
          content: '123-456-7890'
context:
  cards:
    - index: 1
      href: https://d8-uat.boston.gov/departments/digital-team
      title: 'Test Link'
      subtitle: 'Test link with link'
      content: 'Test@Boston.gov'

