title: "circle icons"
handle: "circle_icons"
status: "ready"
context:
  icons:
    - file: "2_tickets.svg"
    - file: "accessibility.svg"
    - file: "alert.svg"
    - file: "alert_red.svg"
    - file: "apple.svg"
    - file: "arobics.svg"
    - file: "b_is_for_boston.svg"
    - file: "bank.svg"
    - file: "baseball.svg"
    - file: "basketball.svg"
    - file: "bathroom.svg"
    - file: "batting_cage.svg"
    - file: "beach.svg"
    - file: "boat.svg"
    - file: "book.svg"
    - file: "boxing_room.svg"
    - file: "building.svg"
    - file: "building_closed.svg"
    - file: "call.svg"
    - file: "camera.svg"
    - file: "cardio.svg"
    - file: "city_councle.svg"
    - file: "city_hall_municipal_offices.svg"
    - file: "closed_roads.svg"
    - file: "coffee.svg"
    - file: "community_centers.svg"
    - file: "community_room.svg"
    - file: "computer.svg"
    - file: "dance_studio.svg"
    - file: "dog_park.svg"
    - file: "event_cancellations.svg"
    - file: "fireworks .svg"
    - file: "fireworks.svg"
    - file: "food.svg"
    - file: "food_truck.svg"
    - file: "football.svg"
    - file: "garden.svg"
    - file: "gym.svg"
    - file: "handball.svg"
    - file: "hiking.svg"
    - file: "indoor_pool.svg"
    - file: "info.svg"
    - file: "kitchen.svg"
    - file: "leaf_and_yard_waste.svg"
    - file: "libraries.svg"
    - file: "location.svg"
    - file: "mail.svg"
    - file: "markets.svg"
    - file: "mask.svg"
    - file: "mbta.svg"
    - file: "moving.svg"
    - file: "music_studio.svg"
    - file: "new_years.svg"
    - file: "no_ice_snow.svg"
    - file: "no_parking.svg"
    - file: "outdoor_pool.svg"
    - file: "outdoor_seating.svg"
    - file: "parking.svg"
    - file: "parking_meters.svg"
    - file: "pencil.svg"
    - file: "people.svg"
    - file: "picnic_area.svg"
    - file: "playground.svg"
    - file: "projectoer.svg"
    - file: "public_art.svg"
    - file: "quote.svg"
    - file: "rock_wall.svg"
    - file: "sauna_steam_room.svg"
    - file: "savings.svg"
    - file: "schools.svg"
    - file: "shower.svg"
    - file: "single_ticket.svg"
    - file: "snow.svg"
    - file: "snow_parking.svg"
    - file: "snow_plows.svg"
    - file: "snow_plows_1.svg"
    - file: "soccer.svg"
    - file: "space_saver.svg"
    - file: "special_events_parade.svg"
    - file: "spin_studio.svg"
    - file: "sports.svg"
    - file: "sports_facility.svg"
    - file: "spray.svg"
    - file: "stage.svg"
    - file: "state_offices.svg"
    - file: "street_sweeping.svg"
    - file: "t.svg"
    - file: "teen_center.svg"
    - file: "tennis_court.svg"
    - file: "tent.svg"
    - file: "tow_lot.svg"
    - file: "track.svg"
    - file: "trash_and_recycling.svg"
    - file: "vendor.svg"
    - file: "weight_room.svg"
    - file: "wellenss.svg"
    - file: "wheel.svg"
    - file: "wifi.svg"
    - file: "yarn.svg"
