/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  ContactForm as CobContactForm
} from './contact-form/contact-form';

declare global {
  interface HTMLCobContactFormElement extends CobContactForm, HTMLElement {
  }
  var HTMLCobContactFormElement: {
    prototype: HTMLCobContactFormElement;
    new (): HTMLCobContactFormElement;
  };
  interface HTMLElementTagNameMap {
    "cob-contact-form": HTMLCobContactFormElement;
  }
  interface ElementTagNameMap {
    "cob-contact-form": HTMLCobContactFormElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "cob-contact-form": JSXElements.CobContactFormAttributes;
    }
  }
  namespace JSXElements {
    export interface CobContactFormAttributes extends HTMLAttributes {
      action?: string;
      defaultSubject?: string;
      to?: string;
      token?: string;
      visible?: boolean;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
