title: Sticky Submenu Mobile
handle: sticky-submenu-mobile
status: ready
# variants:
  # - name: Hub
  #   preview: '@hub'
  # - name: Mini
  #   context:
  #     drawers:
  #       - title: 'Filter by title'
  #         variant: 'dr--sm'
  # - name: JS Controlled
  #   context:
  #     drawers:
  #       - title: 'November 8, 2016: General Election'
  #         subtitle: 'Last updated: 2/2017'
  #         js: true
  #       - title: 'November 8, 2016: General Election'
  #         subtitle: 'Last updated: 2/2017'
  #         js: true
  #         variant: 'dr--open'
context:
  submenu:
    - title: 'Page Sections'
  links:
    - href: https://d8-uat.boston.gov/sites/default/files/linked/file/document_files/2017/03/pdf_for_website_testing_0.pdf
      name: Pay a parking ticket
      # content: "testing content"
      
