title: Quote Card
handle: quote-card
status: ready
preview: '@centered-grey'
variants:
  - name: Hub
    preview: '@centered-hub'
  - name: With image
    context:
      quotes:
        - index: 1
          image:
            url: https://d8-uat.boston.gov/sites/default/files/linked/styles/person_photo_profile_large_360x360_/public/img/person_profile/photos/2017/10/jeanathe-headshot.jpg
            title: 'Jeanethe'
          title: 'Jeanethe'
          location: 'Fenway/Kenmore'
          content: 'I’ve received many opportunities to gain more skills and also further my education.'
  - name: With text
    context:
      quotes:
        - index: 1
          href: 
            url: https://www.boston.gov/neighborhood/allston
            title: 'third space'
          title: 'Jeanethe'
          location: 'Fenway/Kenmore'
          content: 'I’ve received many opportunities to gain more skills and also further my education.'
  - name: with Quotes
    context:
      quotes:
        - index: 1
          image:
            url: https://patterns.boston.gov/images/global/icons/quote.svg
            title: 'Jeanethe'
          title: 'Jeanethe'
          location: 'Fenway/Kenmore'
          content: 'I’ve received many opportunities to gain more skills and also further my education.'
  - name: Grid
    preview: '@grid'
    context:
      quotes:
        - index: 1
          href: 
            url: https://www.boston.gov/neighborhood/allston
            title: 'third space'
          image:
            url: https://patterns.boston.gov/images/global/icons/quote.svg
            title: 'Jeanethe'
          title: 'Jeanethe'
          location: 'Fenway/Kenmore'
          content: 'I’ve received many opportunities to gain more skills and also further my education.'
        - index: 2
          href: 
            url: https://www.boston.gov/neighborhood/allston
            title: 'third space'
          image:
            url: https://patterns.boston.gov/images/global/icons/quote.svg
            title: 'Jeanethe'
          title: 'Jeanethe'
          location: 'Fenway/Kenmore'
          content: 'I’ve received many opportunities to gain more skills and also further my education.'
        - index: 3
          href: 
            url: https://www.boston.gov/neighborhood/allston
            title: 'third space'
          image:
            url: https://patterns.boston.gov/images/global/icons/quote.svg
            title: 'Jeanethe'
          title: 'Jeanethe'
          location: 'Fenway/Kenmore'
          content: 'I’ve received many opportunities to gain more skills and also further my education.'
        - index: 4
          href: 
            url: https://www.boston.gov/neighborhood/allston
            title: 'third space'
          image:
            url: https://patterns.boston.gov/images/global/icons/quote.svg
            title: 'Jeanethe'
          title: 'Jeanethe'
          location: 'Fenway/Kenmore'
          content: 'I’ve received many opportunities to gain more skills and also further my education.'
context:
  quotes:
    - index: 1
      image:
        url: https://patterns.boston.gov/images/global/icons/quote.svg
        title: 'Jeanethe'
      title: 'Jeanethe'
      location: 'Fenway/Kenmore'
      content: 'I’ve received many opportunities to gain more skills and also further my education.'
