title: Quote
handle: quote
status: ready
preview: '@centered-grey'
variants:
  - name: Hub
    preview: '@centered-hub'
  - name: With image
    context:
      quotes:
        - index: 1
          href: https://www.boston.gov/neighborhood/allston
          title: 'Allston'
          content: 'Learn more about one of Boston’s most diverse and active neighborhoods.'
  - name: With text
    context:
      quotes:
        - index: 1
          image:
            url: https://patterns.boston.gov/assets/images/fleet/allston2.jpg
            title: 'Allston'
          href: https://www.boston.gov/neighborhood/allston
          title: 'Allston'
          content: 'Learn more about one of Boston’s most diverse and active neighborhoods.'
  - name: with Quotes
    context:
      quotes:
        - index: 1
          href: https://www.boston.gov/neighborhood/allston
          title: 'Allston'
          subtitle: 'Neighborhood'
          content: 'Learn more about one of Boston’s most diverse and active neighborhoods.'
  - name: Grid
    preview: '@grid'
    context:
      quotes:
        - index: 1
          image:
            url: https://patterns.boston.gov/assets/images/fleet/allston2.jpg
            title: 'Martin J. Walsh'
          href: #
          title: 'Martin J. Walsh'
          subtitle: 'City of Boston'
          content: 'Mayor'
        - index: 2
          image:
            url: https://patterns.boston.gov/assets/images/fleet/allston2.jpg
            title: 'Brian M. Arrigo'
          href: #
          title: 'Brian M. Arrigo'
          subtitle: 'City of Revere'
          content: 'Mayor'
        - index: 3
          image:
            url: https://patterns.boston.gov/assets/images/fleet/allston2.jpg
            title: 'Ann Klee'
          href: #
          title: 'Ann Klee'
          subtitle: 'General Electric'
          content: 'VP, Environmental & Safety, head of Boston operations'
        - index: 4
          image:
            url: https://patterns.boston.gov/assets/images/fleet/allston2.jpg
            title: 'Carol Fulp'
          href: #
          title: 'Carol Fulp'
          subtitle: 'The Partnership'
          content: 'President and CFO'
context:
  quotes:
    - index: 1
      href: https://www.boston.gov/neighborhood/allston
      image:
        url: https://patterns.boston.gov/assets/images/fleet/allston2.jpg
        title: 'Allston'
      title: 'Allston'
      subtitle: 'Neighborhood'
      content: 'Learn more about one of Boston’s most diverse and active neighborhoods.'
